version: "3.3"

services:
  db:
    image: postgres:10
    container_name: url_shortener_db
    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
    volumes:
      - url_shortener_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_web
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/url_shortener
    ports:
    - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    <<: *web
    container_name: url_shortener_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []
    depends_on:
      - web
  redis:
    image: redis:4
    container_name: url_shortener_redis
    expose:
      - 6379
    volumes:
      - url_shortener_redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]

volumes:
  url_shortener_db:
  url_shortener_redis:
